name: Production version bump and quality check

on:
  push:
    branches:
      - master

jobs:
  check:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nodev2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nodev2-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: success()
        run: npm ci --ignore-scripts

      - name: Linting
        if: success()
        run: npm run lint

      - name: Build
        if: success()
        run: npm run build

      - name: Run unit tests
        if: success()
        run: npm run test

      - name: Bump the version & update changelog
        if: success()
        run: npm run version:bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
