name: Pull request (Quality check)

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.12.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Style Linting
        run: npm run lint:style

      - name: Build
        run: npm run build

      - name: Test & Coverage
        run: npm run coverage

      - name: 'Upload Coverage'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
