name: Pull request (Quality check)

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.6.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Linting
        if: success()
        run: npm run lint

      - name: Build
        if: success()
        run: npm run build

      - name: Coverage
        run: npx vitest --coverage.enabled --coverage.provider=v8 --coverage.reporter=json-summary --coverage.reporter=json
